import Head from 'next/head'
import styled from 'styled-components'
import Logo from '../public/logo.svg'
import SimpleSwiper from '../components/Carousel/index'
import Form from '../components/Form/index'
import Login from '../components/Login/index'
import GlobalFooter from '../components/Footer/index' 

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Virgin Experience Days</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <FormBlock>
        <Login />
        <FormInner>
          <Logo className={'logo'} />
 
          <Form />
        </FormInner>
        </FormBlock>
        <ContentBlock>
          <ContentInner>
            <p>What can I do with an account?</p>
            <SimpleSwiper/>
            <GlobalFooter />
          </ContentInner>
        </ContentBlock>
      </Main>
    </Container>
  )
}

const Container = styled.div`
  height: 100vh;
`;

const FormBlock = styled.div`
  display: grid;
  grid-area: form;
  padding: 2rem;
`;

const FormInner = styled.div`
  display: grid;
  grid-template-columns: 1fr 400px 1fr;

  > * {
    grid-column-start: 2;
  }
`;

const ContentBlock = styled.div`
  background-color: #167FE9;
  color: #fff;
  grid-area: content;
  padding: 2rem;
  display: flex;
  justify-content: center;
`;

const ContentInner = styled.div`
  width: 420px;
  display: flex;
  flex-flow: column;

  > p {
    opacity: 0.7;
  }
`;

const Main = styled.main`
  display: grid;
  grid-template-columns: 50% 50%;
  grid-template-areas:
    "form form" 
    "content content";

    @media (min-width: 768px) {
      grid-template-areas: "content form";
    }
  }

  .logo {
    margin-bottom: 16px;
  }
`;
